title: Jaguar Revision A3 for FreeEMS Assembly Manual
header:
  - links
  - prev_next
footer:
  - prev_next
  - footer
structure:
  - index:
    - intro # introductionary chapter
    - index # index (not used yet)
    - footer
  - overview:
    - pcb_overview # overview of the board
  - materials:
    - using_bom # BOM configuration chapter
    - sourcing_components # chapter guiding how to order components
  - general_info:  
    - assembly_tools 
  - assembly_SMD: 
    - assembly_overview # assembly introduction chapter
    - assembly_primary
  - reflow:
    - pcb_bake # instructions how to bake the board in an oven
  - assembly_PowerSupplies:
    - assembly_PS # instructions to assemble the power supplies
  - assembly_MCU_components:
    - assembly_MCU_components # instructions to assemble MCU supporting components
  - assembly_TH_Inputs:
    - assembly_brv
    - assembly_map
    - assembly_rpm
    - assembly_cht
    - assembly_mat
    - assembly_iat
    - assembly_o2
    - assembly_tps
  - assembly_TH_Outputs:
    - assembly_ignition
    - assembly_fuel
    - assembly_injection
  - assembly_pin_strips:
    - assembly_pinstrips
  - testing_inputs:
    - testing_inputs
  - secure_components:
    - secure_components
  - assembly_complete:
    - assembly_complete
  - installation:
    - installation_overview # how to install the Jaguar Revision A3 PCB
    - installation_inputs # how to connect your inputs to the Jaguar Revision A3 PCB
    - installation_outputs # how to connect the outputs from the Jaguar Revision A3 PCB
    - installation_injectors # how to connect the injectors to the Jaguar Revision A3 PCB
